In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [95]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?&page=1', headers=headers).text

In [96]:
soup=BeautifulSoup(webpage,'lxml')

In [97]:
#prettify formt the html pagl
print(soup.prettify())

<html>
 <head>
  <title>
   Access Denied
  </title>
 </head>
 <body>
  <h1>
   Access Denied
  </h1>
  You don't have permission to access "http://www.ambitionbox.com/list-of-companies?" on this server.
  <p>
   Reference #18.e49e1002.1776859200.c982346
  </p>
  <p>
   https://errors.edgesuite.net/18.e49e1002.1776859200.c982346
  </p>
 </body>
</html>

In [98]:
print(soup.prettify())

<html>
 <head>
  <title>
   Access Denied
  </title>
 </head>
 <body>
  <h1>
   Access Denied
  </h1>
  You don't have permission to access "http://www.ambitionbox.com/list-of-companies?" on this server.
  <p>
   Reference #18.e49e1002.1776859200.c982346
  </p>
  <p>
   https://errors.edgesuite.net/18.e49e1002.1776859200.c982346
  </p>
 </body>
</html>

In [99]:
soup=BeautifulSoup(webpage, 'lxml')

company=soup.find_all('div', class_='company-content-wrapper')

In [101]:
len(company)

0

In [119]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
old=[]
employees=[]

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('p', class_='rating').text.strip())
    reviews.append(i.find('a', class_='review-count').text.strip())
    ctype.append(i.find_all('p', class_='infoEntity')[0].text.strip())
    hq.append(i.find_all('p', class_='infoEntity')[1].text.strip())
    old.append(i.find_all('p', class_='infoEntity')[2].text.strip())
    employees.append(i.find_all('p', class_='infoEntity')[3].text.strip())

d={'name':name, 'rating':rating, 'reviews':reviews, 'type':ctype, 'hq':hq, 'old':old, 'employees':employees}

pd.DataFrame(d)

Empty DataFrame
Columns: [name, rating, reviews, type, hq, old, employees]
Index: []

In [109]:
name

[]

In [114]:
rating

[]

In [116]:
review

[]

In [118]:
company

[]

In [120]:
df

Empty DataFrame
Columns: []
Index: []

In [122]:
final=pd.DataFrame()
for j in range(1,11):
    url='https://www.ambitionbox.com/list-of-companies?&page={}'.format()
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get(url, headers=headers).text
soup=BeautifulSoup(webpage,'lxml')
company=soup.find_all('div', class_='company-content-wrapper')
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
old=[]
employees=[]

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('p', class_='rating').text.strip())
    reviews.append(i.find('a', class_='review-count').text.strip())
    ctype.append(i.find_all('p', class_='infoEntity')[0].text.strip())
    hq.append(i.find_all('p', class_='infoEntity')[1].text.strip())
    old.append(i.find_all('p', class_='infoEntity')[2].text.strip())
    employees.append(i.find_all('p', class_='infoEntity')[3].text.strip())

d={'name':name, 'rating':rating, 'reviews':reviews, 'type':ctype, 'hq':hq, 'old':old, 'employees':employees}

pd.DataFrame(d)

IndexError: Replacement index 0 out of range for positional args tuple